# Some text processing functions in sklearn
## CountVectorizer

In [1]:
from sklearn.feature_extraction.text import CountVectorizer

In [2]:
vectorizer = CountVectorizer()
corpus = ['This is the first document.',
          'This is the second second document.',
          'And the third one.',
          'Is this the first document?']
X = vectorizer.fit_transform(corpus)
X

<4x9 sparse matrix of type '<class 'numpy.int64'>'
	with 19 stored elements in Compressed Sparse Row format>

In [3]:
vectorizer.get_feature_names()

['and', 'document', 'first', 'is', 'one', 'second', 'the', 'third', 'this']

In [4]:
X.toarray()

array([[0, 1, 1, 1, 0, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 2, 1, 0, 1],
       [1, 0, 0, 0, 1, 0, 1, 1, 0],
       [0, 1, 1, 1, 0, 0, 1, 0, 1]])

In [5]:
vectorizer.transform(['Something completely new.']).toarray()

array([[0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [6]:
vectorizer.transform(['A document with repeated document word']).toarray()

array([[0, 2, 0, 0, 0, 0, 0, 0, 0]])

In [7]:
from sklearn.metrics.pairwise import cosine_similarity

In [8]:
cosine_similarity(X)

array([[1.        , 0.63245553, 0.2236068 , 1.        ],
       [0.63245553, 1.        , 0.1767767 , 0.63245553],
       [0.2236068 , 0.1767767 , 1.        , 0.2236068 ],
       [1.        , 0.63245553, 0.2236068 , 1.        ]])

# TfidfVectorizer

In [9]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer()
X_tfidf = vectorizer.fit_transform(corpus)
X_tfidf

<4x9 sparse matrix of type '<class 'numpy.float64'>'
	with 19 stored elements in Compressed Sparse Row format>

In [10]:
X_tfidf.toarray()

array([[0.        , 0.43877674, 0.54197657, 0.43877674, 0.        ,
        0.        , 0.35872874, 0.        , 0.43877674],
       [0.        , 0.27230147, 0.        , 0.27230147, 0.        ,
        0.85322574, 0.22262429, 0.        , 0.27230147],
       [0.55280532, 0.        , 0.        , 0.        , 0.55280532,
        0.        , 0.28847675, 0.55280532, 0.        ],
       [0.        , 0.43877674, 0.54197657, 0.43877674, 0.        ,
        0.        , 0.35872874, 0.        , 0.43877674]])

In [11]:
cosine_similarity(X_tfidf)

array([[1.        , 0.43830038, 0.1034849 , 1.        ],
       [0.43830038, 1.        , 0.06422193, 0.43830038],
       [0.1034849 , 0.06422193, 1.        , 0.1034849 ],
       [1.        , 0.43830038, 0.1034849 , 1.        ]])

## HashingVectorizer

In [12]:
from sklearn.feature_extraction.text import HashingVectorizer
hv = HashingVectorizer(n_features=5)
hv.transform(corpus).toarray()

array([[ 0.        , -0.57735027,  0.57735027, -0.57735027,  0.        ],
       [ 0.81649658,  0.        ,  0.40824829, -0.40824829,  0.        ],
       [-0.5       ,  0.5       ,  0.        , -0.5       , -0.5       ],
       [ 0.        , -0.57735027,  0.57735027, -0.57735027,  0.        ]])

In [13]:
cosine_similarity(hv.transform(corpus))

array([[ 1.        ,  0.47140452,  0.        ,  1.        ],
       [ 0.47140452,  1.        , -0.20412415,  0.47140452],
       [ 0.        , -0.20412415,  1.        ,  0.        ],
       [ 1.        ,  0.47140452,  0.        ,  1.        ]])

# An Example of Text Clustering
Let's use the tweet data set from assignment 2 ... because we can.

In [14]:
import pandas as pd
tweets_pd = pd.read_json("10000 tweets_clean.zip")
tweets_pd.head()

id objectType                                              actor  \
0  1.497157e+20   activity  {'objectType': 'person', 'id': '10243188921458...   
1  1.497157e+20   activity  {'objectType': 'person', 'id': '1024397578801'...   
2  1.497157e+20   activity  {'objectType': 'person', 'id': '10243126525057...   
3  1.497157e+20   activity  {'objectType': 'person', 'id': '10243295689843...   
4  1.497157e+20   activity  {'objectType': 'person', 'id': '1024318064228'...   

   verb                postedTime  \
0  post  2016-04-01T00:00:01.000Z   
1  post  2016-04-01T00:00:01.000Z   
2  post  2016-04-01T00:00:01.000Z   
3  post  2016-04-01T00:00:03.000Z   
4  post  2016-04-01T00:00:00.000Z   

                                           generator  \
0  {'displayName': 'Facebook', 'link': 'http://ww...   
1  {'displayName': 'Weather Display Tweet', 'link...   
2  {'displayName': 'Sprinklr', 'link': 'http://ww...   
3  {'displayName': 'Facebook', 'link': 'http://ww...   
4  {'displayName': 'HubSpot', 'link': 'http://www...   

                                            provider  \
0  {'objectType': 'service', 'displayName': 'Twit...   
1  {'objectType': 'service', 'displayName': 'Twit...   
2  {'objectType': 'service', 'displayName': 'Twit...   
3  {'objectType': 'service', 'displayName': 'Twit...   
4  {'objectType': 'service', 'displayName': 'Twit...   

                                                link  \
0  http://twitter.com/losebabyweight1/statuses/71...   
1  http://twitter.com/wantirnaweather/statuses/71...   
2  http://twitter.com/sas_anz/statuses/7156901408...   
3  http://twitter.com/Letticlothing/statuses/7156...   
4  http://twitter.com/Intelledox/statuses/7156901...   

                                                text  \
0  CONGRATULATIONS Suzie Walker on both your beau...   
1  Wantirna, VIC, AU 11:00 AM Temp 19.8°C, RH 67p...   
2  Join us @ the Hilton Sydney 2 learn how 2 make...   
3  Say Hello to this Gorgeous Gingham Dress! \n\n...   
4  Register for #Convergence2016 to hear@ChelleMe...   

                                              object  ...  \
0  {'objectType': 'note', 'id': '1345715690143449...  ...   
1  {'objectType': 'note', 'id': '1345715690141306...  ...   
2  {'objectType': 'note', 'id': '1345715690140849...  ...   
3  {'objectType': 'note', 'id': '1345715690148764...  ...   
4  {'objectType': 'note', 'id': '1345715690137900...  ...   

                                    twitter_entities twitter_filter_level  \
0  {'hashtags': [], 'urls': [{'url': 'https://t.c...                  low   
1  {'hashtags': [{'text': 'vicweather', 'indices'...                  low   
2  {'hashtags': [], 'urls': [{'url': 'https://t.c...                  low   
3  {'hashtags': [], 'urls': [{'url': 'https://t.c...                  low   
4  {'hashtags': [{'text': 'Convergence2016', 'ind...                  low   

  twitter_lang retweetCount  \
0           en            0   
1           en            0   
2           en            0   
3           en            0   
4           en            0   

                                                gnip  \
0  {'matching_rules': [{'value': 'bio_location: "...   
1  {'matching_rules': [{'value': 'bio_location: "...   
2  {'matching_rules': [{'value': 'bio_location: "...   
3  {'matching_rules': [{'value': 'bio_location: "...   
4  {'matching_rules': [{'value': 'bio_location: "...   

                           twitter_extended_entities inReplyTo  \
0                                                NaN       NaN   
1                                                NaN       NaN   
2  {'media': [{'id': 'NumberLong(1569014044273459...       NaN   
3                                                NaN       NaN   
4                                                NaN       NaN   

  twitter_quoted_status location  geo  
0                   NaN      NaN  NaN  
1                   NaN      NaN  NaN  
2                   NaN      NaN  NaN  
3                   NaN      NaN  NaN  
4   

In [15]:
tweets_vectorizer = TfidfVectorizer()
vectors = tweets_vectorizer.fit_transform(tweets_pd.text)
vectors

<10000x31628 sparse matrix of type '<class 'numpy.float64'>'
	with 139080 stored elements in Compressed Sparse Row format>

In [16]:
from sklearn.cluster import KMeans
kmeans = KMeans(n_clusters=10, random_state=0).fit(vectors)

In [17]:
kmeans.predict(vectors[:5])

array([2, 5, 1, 1, 1], dtype=int32)

# Topic Modelling
Watch http://stat-graphics.org/movies/ldavis.html for an example of the use of pyLDAvis

In [18]:
from sklearn.decomposition import LatentDirichletAllocation
import pyLDAvis
import pyLDAvis.sklearn

/home/diego/.vscode/extensions/ms-python.python-2020.9.111407/pythonFiles/lib/python/past/types/oldstr.py:23: DeprecationWarning: invalid escape sequence \d
  """


In [19]:
lda_model = LatentDirichletAllocation(n_components=20, # Number of topics
                                      learning_method='online', # Faster when using large volumes of data
                                      random_state=0,       
                                      n_jobs = -1  # Use all available CPUs
                                     )

In [20]:
lda_output = lda_model.fit_transform(vectors)

In [21]:
pyLDAvis.enable_notebook()
pyLDAvis.sklearn.prepare(lda_model, vectors, tweets_vectorizer, mds='tsne')

PreparedData(topic_coordinates=                x           y  topics  cluster       Freq
topic                                                    
16     -10.878068   10.538728       1        1  52.609678
14     -60.884026  -75.591820       2        1   6.455727
1       -2.336119  -53.289074       3        1   4.819179
7      -61.385319  -12.914634       4        1   3.147883
11     -28.737743  126.296997       5        1   2.832482
10       1.066606 -123.552811       6        1   2.730105
2       45.140720   -7.947869       7        1   2.660750
6     -140.795975  -98.530548       8        1   2.528506
19      61.531681  -83.240562       9        1   2.347955
15     -72.563057 -140.396881      10        1   2.319342
13      15.984491   63.578186      11        1   2.086700
4     -160.851624   68.945145      12        1   2.035473
5       85.961830   51.922935      13        1   1.840251
17     -99.020836  109.936348      14        1   1.834214
0     -176.764130   -8.681684      15        1   1.816266
12    -117.189880  -37.420200      16        1   1.645056
8      108.829918  -22.946203      17        1   1.616249
3       47.588097  121.934814      18        1   1.592541
9     -106.467834   30.176889      19        1   1.564675
18     -50.613804   59.328842      20        1   1.516966, topic_info=               Term        Freq       Total Category  logprob  loglift
13122  iheartawards   41.000000   41.000000  Default  30.0000  30.0000
4075    bestfanarmy   41.000000   41.000000  Default  29.0000  29.0000
26166           the  227.000000  227.000000  Default  28.0000  28.0000
1052        5sosfam   35.000000   35.000000  Default  27.0000  27.0000
6211             co  277.000000  277.000000  Default  26.0000  26.0000
...             ...         ...         ...      ...      ...      ...
673             385    0.264272    0.633506  Topic20  -7.5577   3.3142
1567     9txp78e5yx    0.259040    0.628273  Topic20  -7.5777   3.3025
6211             co    1.244810  277.625812  Topic20  -6.0080  -1.2188
12783         https    1.207587  288.042178  Topic20  -6.0383  -1.2860
22926            rt    0.451061  217.302761  Topic20  -7.0231  -1.9890

[728 rows x 6 columns], token_table=       Topic      Freq   Term
term                         
19         4  0.587692     04
130        1  0.869201     10
130        4  0.079018     10
173        1  0.688973     11
173        4  0.275589     11
...      ...       ...    ...
31523     17  0.888785     없을
31549     17  0.888785    인간의
31595     17  0.888785  탑골공원의
31610     17  0.888785    할배를
31611     17  0.888785     해도

[612 rows x 3 columns], R=30, lambda_step=0.01, plot_opts={'xlab': 'PC1', 'ylab': 'PC2'}, topic_order=[17, 15, 2, 8, 12, 11, 3, 7, 20, 16, 14, 5, 6, 18, 1, 13, 9, 4, 10, 19])

Topic 1 is much larger than the rest. If you hover over topic 1 you will see that most of the words are stop words (which we have not removed). Let's remove stop words and repeat the analysis.

In [22]:
tweets_vectorizer_nonstop = TfidfVectorizer(stop_words="english")
vectors_nonstop = tweets_vectorizer_nonstop.fit_transform(tweets_pd.text)
vectors_nonstop

<10000x31356 sparse matrix of type '<class 'numpy.float64'>'
	with 94731 stored elements in Compressed Sparse Row format>

In [23]:
lda_model_nonstop = LatentDirichletAllocation(n_components=20, # Number of topics
                                              learning_method='online', # Faster when using large volumes of data
                                              random_state=0,       
                                              n_jobs = -1  # Use all available CPUs
                                              )

In [24]:
lda_output_nonstop = lda_model_nonstop.fit_transform(vectors_nonstop)

In [25]:
lda_vectors = pd.DataFrame(lda_output_nonstop)
lda_vectors.columns = ['Topic '+str(i) for i in range(lda_vectors.shape[1])]
lda_vectors.index = ['Document '+str(i) for i in range(lda_vectors.shape[0])]
lda_vectors.head()

Topic 0   Topic 1   Topic 2   Topic 3   Topic 4   Topic 5  \
Document 0  0.011602  0.011602  0.011602  0.665906  0.070398  0.011602   
Document 1  0.009266  0.009266  0.009266  0.009266  0.009266  0.823940   
Document 2  0.011488  0.011488  0.011488  0.084480  0.011488  0.011488   
Document 3  0.010898  0.010898  0.010898  0.010898  0.010898  0.010898   
Document 4  0.011958  0.011958  0.011958  0.695736  0.011958  0.011958   

             Topic 6   Topic 7   Topic 8   Topic 9  Topic 10  Topic 11  \
Document 0  0.011602  0.011602  0.011602  0.011602  0.011602  0.011602   
Document 1  0.009266  0.009266  0.009266  0.009266  0.009266  0.009266   
Document 2  0.011488  0.011488  0.011488  0.070430  0.011488  0.118989   
Document 3  0.010898  0.010898  0.010898  0.010898  0.010898  0.010898   
Document 4  0.089022  0.011958  0.011958  0.011958  0.011958  0.011958   

            Topic 12  Topic 13  Topic 14  Topic 15  Topic 16  Topic 17  \
Document 0  0.011602  0.011602  0.066457  0.011602  0.011602  0.011602   
Document 1  0.009266  0.009266  0.009266  0.009266  0.009266  0.009266   
Document 2  0.011488  0.011488  0.056706  0.011488  0.011488  0.497072   
Document 3  0.010898  0.010898  0.792945  0.010898  0.010898  0.010898   
Document 4  0.011958  0.011958  0.011958  0.011958  0.011958  0.011958   

            Topic 18  Topic 19  
Document 0  0.011602  0.011602  
Document 1  0.009266  0.009266  
Document 2  0.011488  0.011488  
Document 3  0.010898  0.010898  
Document 4  0.011958  0.011958

In [26]:
pyLDAvis.sklearn.prepare(lda_model_nonstop, vectors_nonstop, tweets_vectorizer_nonstop, mds='tsne')

PreparedData(topic_coordinates=                x           y  topics  cluster       Freq
topic                                                    
0      -10.878068   10.538728       1        1  13.471159
14     -60.884026  -75.591820       2        1  10.793979
15      -2.336119  -53.289074       3        1   7.106522
6      -61.385319  -12.914634       4        1   7.030021
4      -28.737743  126.296997       5        1   6.590226
2        1.066606 -123.552811       6        1   6.317491
11      45.140720   -7.947869       7        1   5.813912
1     -140.795975  -98.530548       8        1   5.750405
3       61.531681  -83.240562       9        1   5.731196
5      -72.563057 -140.396881      10        1   5.401742
9       15.984491   63.578186      11        1   3.728334
19    -160.851624   68.945145      12        1   3.265792
10      85.961830   51.922935      13        1   3.130745
7      -99.020836  109.936348      14        1   2.681967
8     -176.764130   -8.681684      15        1   2.430989
16    -117.189880  -37.420200      16        1   2.363537
12     108.829918  -22.946203      17        1   2.291891
18      47.588097  121.934814      18        1   2.085779
13    -106.467834   30.176889      19        1   2.068204
17     -50.613804   59.328842      20        1   1.946109, topic_info=                 Term       Freq       Total Category  logprob  loglift
13007    iheartawards  41.000000   41.000000  Default  30.0000  30.0000
4032      bestfanarmy  41.000000   41.000000  Default  29.0000  29.0000
1052          5sosfam  35.000000   35.000000  Default  28.0000  28.0000
1892         activist  34.000000   34.000000  Default  27.0000  27.0000
6082          clinton  26.000000   26.000000  Default  26.0000  26.0000
...               ...        ...         ...      ...      ...      ...
31046         美風藍だよねヽ   0.330108    0.755146  Topic20  -7.4225   3.1118
2463     alyciajdebnm   0.330100    0.755138  Topic20  -7.4225   3.1118
22734      rsovatqxqd   0.328962    0.754000  Topic20  -7.4260   3.1099
24896  strangelopunny   0.324303    0.749341  Topic20  -7.4403   3.1018
12670           https   2.280648  234.537086  Topic20  -5.4897  -0.6938

[811 rows x 6 columns], token_table=       Topic      Freq   Term
term                         
1          2  0.984064    000
130       10  0.941009     10
173        7  0.161510     11
173       10  0.807551     11
185        1  0.505700     12
...      ...       ...    ...
31251     19  0.825692     없을
31277     19  0.825692    인간의
31323     19  0.825692  탑골공원의
31338     19  0.825692    할배를
31339     19  0.825692     해도

[959 rows x 3 columns], R=30, lambda_step=0.01, plot_opts={'xlab': 'PC1', 'ylab': 'PC2'}, topic_order=[1, 15, 16, 7, 5, 3, 12, 2, 4, 6, 10, 20, 11, 8, 9, 17, 13, 19, 14, 18])

In [27]:
# Function from https://towardsdatascience.com/topic-modeling-quora-questions-with-lda-nmf-aff8dce5e1dd
import numpy as np
def show_topics(vectorizer=vectorizer, lda_model=lda_model, n_words=20):
    keywords = np.array(vectorizer.get_feature_names())
    topic_keywords = []
    for topic_weights in lda_model.components_:
        top_keyword_locs = (-topic_weights).argsort()[:n_words]
        topic_keywords.append(keywords.take(top_keyword_locs))
    return topic_keywords

topic_keywords = show_topics(vectorizer=tweets_vectorizer, lda_model=lda_model, n_words=20)

df_topic_keywords = pd.DataFrame(topic_keywords)
df_topic_keywords.columns = ['Word '+str(i) for i in range(df_topic_keywords.shape[1])]
df_topic_keywords.index = ['Topic '+str(i) for i in range(df_topic_keywords.shape[0])]
df_topic_keywords.T

Topic 0         Topic 1      Topic 2          Topic 3  \
Word 0            lt           https       middle              más   
Word 1       tornado              co        brown           budget   
Word 2          jade  hillaryclinton          cup              las   
Word 3         thecw              rt         code             الله   
Word 4      samantha        imsosick         mind            cries   
Word 5         hit30         college           co              les   
Word 6    decreasing  weeklystandard         dies              una   
Word 7   jpdice_fox6   greenpeaceusa         zaha              boo   
Word 8           ugh            lies        https        hachortle   
Word 9          king          murder      fashion               es   
Word 10         hail        adelaide        hadid            touch   
Word 11           co            then      details              على   
Word 12        https          police   queensland         paradise   
Word 13         wide           labor          cat  inttravellermag   
Word 14         você            luck          kid        dreamhunx   
Word 15      haircut       calum5sos  feelthebern     mindingminee   
Word 16  msgunderson        activist        staff      sieepysmile   
Word 17         till            went      octavia          olympic   
Word 18        amiga            hell   benjealous           tester   
Word 19        aloud       trump2016           45         dropping   

             Topic 4          Topic 5        Topic 6    Topic 7  Topic 8  \
Word 0           nsw           launch     ashton5sos         gt    daddy   
Word 1       bts_twt         politics   aldubyayawho         co       co   
Word 2            em         brussels            pre      https     poor   
Word 3         scott            chris        million       wind    https   
Word 4      snapchat      shutdownchi             sa         km      할배를   
Word 5            rt  fightforfunding        preview     design      승부를   
Word 6    5soslocate               rt         resist      takes     뒤엎어서   
Word 7            co           nights        alabama         11      악의를   
Word 8       michael               co        slackhq     league       해도   
Word 9   kyliejenner            https         isobar  gmeagency     뛰어나다   
Word 10          por          reviews     qnm9sfakf8   comments      인간의   
Word 11  development             hunt     dave_budge       pips    탑골공원의   
Word 12        https            plays       counties   terrible       없을   
Word 13       arthur               لا             st   aviation    당해낼수는   
Word 14        leads          xamarin  nwsbirmingham         mm      아무리   
Word 15    overnight          attacks           alwx         te      무효로   
Word 16    sinodinos       foundation         studio   humidity     무시하지   
Word 17   5sos_daily       enterprise      democracy         10     바둑판을   
Word 18     creating             doll             oz   pictures       마라   
Word 19        favor               35             mo       flew  abmanse   

                  Topic 9         Topic 10  Topic 11        Topic 12  \
Word 0             assets               de        co         digital   
Word 1             unlcba         congrats     https              co   
Word 2         trademarks              que     loses           https   
Word 3        mikaylamack  georgianasophia      fuck              ty   
Word 4         intangible               eu   western        thankyou   
Word 5      thekooriwoman             bird      tour             tak   
Word 6                 co       yyncyhvcyh    happen              rt   
Word 7              https               na   checked         alhanda   
Word 8             secure            three     water         grilled   
Word 9   wisconsinprimary               se  download              dj   
Word 10             promo               co      hour           salad   
Word 11          susmac16            https       her            bean   
Word 12  