# Some text processing functions in sklearn
## CountVectorizer

In [1]:
from sklearn.feature_extraction.text import CountVectorizer

In [2]:
vectorizer = CountVectorizer()
corpus = ['This is the first document.',
          'This is the second second document.',
          'And the third one.',
          'Is this the first document?']
X = vectorizer.fit_transform(corpus)
X

<4x9 sparse matrix of type '<class 'numpy.int64'>'
	with 19 stored elements in Compressed Sparse Row format>

In [3]:
vectorizer.get_feature_names()

['and', 'document', 'first', 'is', 'one', 'second', 'the', 'third', 'this']

In [4]:
X.toarray()

array([[0, 1, 1, 1, 0, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 2, 1, 0, 1],
       [1, 0, 0, 0, 1, 0, 1, 1, 0],
       [0, 1, 1, 1, 0, 0, 1, 0, 1]])

In [5]:
vectorizer.transform(['Something completely new.']).toarray()

array([[0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [6]:
vectorizer.transform(['A document with repeated document word']).toarray()

array([[0, 2, 0, 0, 0, 0, 0, 0, 0]])

In [7]:
from sklearn.metrics.pairwise import cosine_similarity

In [8]:
cosine_similarity(X)

array([[1.        , 0.63245553, 0.2236068 , 1.        ],
       [0.63245553, 1.        , 0.1767767 , 0.63245553],
       [0.2236068 , 0.1767767 , 1.        , 0.2236068 ],
       [1.        , 0.63245553, 0.2236068 , 1.        ]])

# TfidfVectorizer

In [9]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer()
X_tfidf = vectorizer.fit_transform(corpus)
X_tfidf

<4x9 sparse matrix of type '<class 'numpy.float64'>'
	with 19 stored elements in Compressed Sparse Row format>

In [10]:
X_tfidf.toarray()

array([[0.        , 0.43877674, 0.54197657, 0.43877674, 0.        ,
        0.        , 0.35872874, 0.        , 0.43877674],
       [0.        , 0.27230147, 0.        , 0.27230147, 0.        ,
        0.85322574, 0.22262429, 0.        , 0.27230147],
       [0.55280532, 0.        , 0.        , 0.        , 0.55280532,
        0.        , 0.28847675, 0.55280532, 0.        ],
       [0.        , 0.43877674, 0.54197657, 0.43877674, 0.        ,
        0.        , 0.35872874, 0.        , 0.43877674]])

In [11]:
cosine_similarity(X_tfidf)

array([[1.        , 0.43830038, 0.1034849 , 1.        ],
       [0.43830038, 1.        , 0.06422193, 0.43830038],
       [0.1034849 , 0.06422193, 1.        , 0.1034849 ],
       [1.        , 0.43830038, 0.1034849 , 1.        ]])

## HashingVectorizer

In [12]:
from sklearn.feature_extraction.text import HashingVectorizer
hv = HashingVectorizer(n_features=5)
hv.transform(corpus).toarray()

array([[ 0.        , -0.57735027,  0.57735027, -0.57735027,  0.        ],
       [ 0.81649658,  0.        ,  0.40824829, -0.40824829,  0.        ],
       [-0.5       ,  0.5       ,  0.        , -0.5       , -0.5       ],
       [ 0.        , -0.57735027,  0.57735027, -0.57735027,  0.        ]])

In [13]:
cosine_similarity(hv.transform(corpus))

array([[ 1.        ,  0.47140452,  0.        ,  1.        ],
       [ 0.47140452,  1.        , -0.20412415,  0.47140452],
       [ 0.        , -0.20412415,  1.        ,  0.        ],
       [ 1.        ,  0.47140452,  0.        ,  1.        ]])

# An Example of Text Clustering
Let's use the tweet data set from assignment 2 ... because we can.

In [14]:
import pandas as pd
tweets_pd = pd.read_json("10000 tweets_clean.zip")
tweets_pd.head()

id objectType                                              actor  \
0  1.497157e+20   activity  {'objectType': 'person', 'id': '10243188921458...   
1  1.497157e+20   activity  {'objectType': 'person', 'id': '1024397578801'...   
2  1.497157e+20   activity  {'objectType': 'person', 'id': '10243126525057...   
3  1.497157e+20   activity  {'objectType': 'person', 'id': '10243295689843...   
4  1.497157e+20   activity  {'objectType': 'person', 'id': '1024318064228'...   

   verb                postedTime  \
0  post  2016-04-01T00:00:01.000Z   
1  post  2016-04-01T00:00:01.000Z   
2  post  2016-04-01T00:00:01.000Z   
3  post  2016-04-01T00:00:03.000Z   
4  post  2016-04-01T00:00:00.000Z   

                                           generator  \
0  {'displayName': 'Facebook', 'link': 'http://ww...   
1  {'displayName': 'Weather Display Tweet', 'link...   
2  {'displayName': 'Sprinklr', 'link': 'http://ww...   
3  {'displayName': 'Facebook', 'link': 'http://ww...   
4  {'displayName': 'HubSpot', 'link': 'http://www...   

                                            provider  \
0  {'objectType': 'service', 'displayName': 'Twit...   
1  {'objectType': 'service', 'displayName': 'Twit...   
2  {'objectType': 'service', 'displayName': 'Twit...   
3  {'objectType': 'service', 'displayName': 'Twit...   
4  {'objectType': 'service', 'displayName': 'Twit...   

                                                link  \
0  http://twitter.com/losebabyweight1/statuses/71...   
1  http://twitter.com/wantirnaweather/statuses/71...   
2  http://twitter.com/sas_anz/statuses/7156901408...   
3  http://twitter.com/Letticlothing/statuses/7156...   
4  http://twitter.com/Intelledox/statuses/7156901...   

                                                text  \
0  CONGRATULATIONS Suzie Walker on both your beau...   
1  Wantirna, VIC, AU 11:00 AM Temp 19.8°C, RH 67p...   
2  Join us @ the Hilton Sydney 2 learn how 2 make...   
3  Say Hello to this Gorgeous Gingham Dress! \n\n...   
4  Register for #Convergence2016 to hear@ChelleMe...   

                                              object  ...  \
0  {'objectType': 'note', 'id': '1345715690143449...  ...   
1  {'objectType': 'note', 'id': '1345715690141306...  ...   
2  {'objectType': 'note', 'id': '1345715690140849...  ...   
3  {'objectType': 'note', 'id': '1345715690148764...  ...   
4  {'objectType': 'note', 'id': '1345715690137900...  ...   

                                    twitter_entities twitter_filter_level  \
0  {'hashtags': [], 'urls': [{'url': 'https://t.c...                  low   
1  {'hashtags': [{'text': 'vicweather', 'indices'...                  low   
2  {'hashtags': [], 'urls': [{'url': 'https://t.c...                  low   
3  {'hashtags': [], 'urls': [{'url': 'https://t.c...                  low   
4  {'hashtags': [{'text': 'Convergence2016', 'ind...                  low   

  twitter_lang retweetCount  \
0           en            0   
1           en            0   
2           en            0   
3           en            0   
4           en            0   

                                                gnip  \
0  {'matching_rules': [{'value': 'bio_location: "...   
1  {'matching_rules': [{'value': 'bio_location: "...   
2  {'matching_rules': [{'value': 'bio_location: "...   
3  {'matching_rules': [{'value': 'bio_location: "...   
4  {'matching_rules': [{'value': 'bio_location: "...   

                           twitter_extended_entities inReplyTo  \
0                                                NaN       NaN   
1                                                NaN       NaN   
2  {'media': [{'id': 'NumberLong(1569014044273459...       NaN   
3                                                NaN       NaN   
4                                                NaN       NaN   

  twitter_quoted_status location  geo  
0                   NaN      NaN  NaN  
1                   NaN      NaN  NaN  
2                   NaN      NaN  NaN  
3                   NaN      NaN  NaN  
4   

In [15]:
tweets_vectorizer = TfidfVectorizer()
vectors = tweets_vectorizer.fit_transform(tweets_pd.text)
vectors

<10000x31628 sparse matrix of type '<class 'numpy.float64'>'
	with 139080 stored elements in Compressed Sparse Row format>

In [16]:
from sklearn.cluster import KMeans
kmeans = KMeans(n_clusters=10, random_state=0).fit(vectors)

In [17]:
kmeans.predict(vectors[:5])

array([2, 5, 1, 1, 1], dtype=int32)

# Topic Modelling
Watch http://stat-graphics.org/movies/ldavis.html for an example of the use of pyLDAvis

In [18]:
from sklearn.decomposition import LatentDirichletAllocation
import pyLDAvis
import pyLDAvis.sklearn

In [19]:
lda_model = LatentDirichletAllocation(n_components=20, # Number of topics
                                      learning_method='online', # Faster when using large volumes of data
                                      random_state=0,       
                                      n_jobs = -1  # Use all available CPUs
                                     )

LatentDirichetAllocation needs to use count vectors. This is because of the nature of their algorithm. For further details, read this discussion: https://datascience.stackexchange.com/questions/21950/why-we-should-not-feed-lda-with-tfidf

In [20]:
count_vectorizer = CountVectorizer()
count_vectors = count_vectorizer.fit_transform(tweets_pd.text)
lda_output = lda_model.fit_transform(count_vectors)

In [21]:
pyLDAvis.enable_notebook()
pyLDAvis.sklearn.prepare(lda_model, count_vectors, count_vectorizer, mds='tsne')

PreparedData(topic_coordinates=                x           y  topics  cluster       Freq
topic                                                    
1      -10.878068   10.538728       1        1  25.946027
16     -60.884026  -75.591820       2        1  24.218397
11      -2.336119  -53.289074       3        1  10.219478
6      -61.385319  -12.914634       4        1   4.679555
2      -28.737743  126.296997       5        1   3.950211
13       1.066606 -123.552811       6        1   2.482677
4       45.140720   -7.947869       7        1   2.428472
15    -140.795975  -98.530548       8        1   2.383672
18      61.531681  -83.240562       9        1   2.321786
0      -72.563057 -140.396881      10        1   2.296693
7       15.984491   63.578186      11        1   2.174681
14    -160.851624   68.945145      12        1   2.110063
3       85.961830   51.922935      13        1   2.014335
10     -99.020836  109.936348      14        1   2.013023
9     -176.764130   -8.681684      15        1   2.000392
17    -117.189880  -37.420200      16        1   1.944896
8      108.829918  -22.946203      17        1   1.822664
19      47.588097  121.934814      18        1   1.782428
5     -106.467834   30.176889      19        1   1.663031
12     -50.613804   59.328842      20        1   1.547519, topic_info=            Term         Freq        Total Category  logprob  loglift
12783      https  6217.000000  6217.000000  Default  30.0000  30.0000
6211          co  5700.000000  5700.000000  Default  29.0000  29.0000
22926         rt  3894.000000  3894.000000  Default  28.0000  28.0000
29820        you  1318.000000  1318.000000  Default  27.0000  27.0000
26678         to  2669.000000  2669.000000  Default  26.0000  26.0000
...          ...          ...          ...      ...      ...      ...
8191       dobbs     5.826949     6.529019  Topic20  -5.9643   4.0548
13293  including     5.797698     6.499768  Topic20  -5.9693   4.0542
19191  obviously     5.705019     6.407089  Topic20  -5.9854   4.0525
25704        tak     5.213564     5.915634  Topic20  -6.0755   4.0422
22926         rt    39.103099  3894.645283  Topic20  -4.0606  -0.4326

[771 rows x 6 columns], token_table=       Topic      Freq   Term
term                         
19        11  0.952599     04
130       11  0.984335     10
173       11  0.968002     11
185        5  0.724934     12
185       11  0.249196     12
...      ...       ...    ...
31523     20  0.956515     없을
31549     20  0.956515    인간의
31595     20  0.956515  탑골공원의
31610     20  0.956515    할배를
31611     20  0.956515     해도

[850 rows x 3 columns], R=30, lambda_step=0.01, plot_opts={'xlab': 'PC1', 'ylab': 'PC2'}, topic_order=[2, 17, 12, 7, 3, 14, 5, 16, 19, 1, 8, 15, 4, 11, 10, 18, 9, 20, 6, 13])

Topics 1 and 2 are much larger than the rest. If you hover over them you will see that most of the words are stop words (which we have not removed). Let's remove stop words and repeat the analysis.

In [22]:
count_vectorizer_nonstop = CountVectorizer(stop_words="english")
count_vectors_nonstop = count_vectorizer_nonstop.fit_transform(tweets_pd.text)
count_vectors_nonstop

<10000x31356 sparse matrix of type '<class 'numpy.int64'>'
	with 94731 stored elements in Compressed Sparse Row format>

In [23]:
lda_model_nonstop = LatentDirichletAllocation(n_components=20, # Number of topics
                                              learning_method='online', # Faster when using large volumes of data
                                              random_state=0,       
                                              n_jobs = -1  # Use all available CPUs
                                              )

In [24]:
lda_output_nonstop = lda_model_nonstop.fit_transform(count_vectors_nonstop)

In [28]:
pyLDAvis.sklearn.prepare(lda_model_nonstop, count_vectors_nonstop, count_vectorizer_nonstop, mds='tsne')

PreparedData(topic_coordinates=                x           y  topics  cluster      Freq
topic                                                   
0      -10.878068   10.538728       1        1  9.605138
14     -60.884026  -75.591820       2        1  9.272383
19      -2.336119  -53.289074       3        1  9.022723
4      -61.385319  -12.914634       4        1  7.285080
5      -28.737743  126.296997       5        1  6.434883
2        1.066606 -123.552811       6        1  6.194817
9       45.140720   -7.947869       7        1  5.997001
11    -140.795975  -98.530548       8        1  4.644061
6       61.531681  -83.240562       9        1  4.449635
12     -72.563057 -140.396881      10        1  4.037182
10      15.984491   63.578186      11        1  3.967104
18    -160.851624   68.945145      12        1  3.694554
1       85.961830   51.922935      13        1  3.578972
13     -99.020836  109.936348      14        1  3.518566
3     -176.764130   -8.681684      15        1  3.434172
17    -117.189880  -37.420200      16        1  3.176202
8      108.829918  -22.946203      17        1  3.133646
16      47.588097  121.934814      18        1  2.993368
7     -106.467834   30.176889      19        1  2.878983
15     -50.613804   59.328842      20        1  2.681530, topic_info=               Term         Freq        Total Category  logprob  loglift
22744            rt  3462.000000  3462.000000  Default  30.0000  30.0000
12670         https  5370.000000  5370.000000  Default  29.0000  29.0000
27375         union   222.000000   222.000000  Default  28.0000  28.0000
13007  iheartawards   252.000000   252.000000  Default  27.0000  27.0000
4032    bestfanarmy   252.000000   252.000000  Default  26.0000  26.0000
...             ...          ...          ...      ...      ...      ...
1754        abmanse     6.972328     7.677911  Topic20  -5.9299   3.5224
31323         탑골공원의     6.972328     7.677911  Topic20  -5.9299   3.5224
31165          무시하지     6.972328     7.677911  Topic20  -5.9299   3.5224
29390          yang     6.751595     7.457167  Topic20  -5.9621   3.5194
20573   politicians     6.713917     7.419490  Topic20  -5.9677   3.5189

[734 rows x 6 columns], token_table=       Topic      Freq   Term
term                         
1          2  0.991500    000
130       12  0.985411     10
173       12  0.981584     11
185        1  0.983528     12
233        1  0.983240     15
...      ...       ...    ...
31251     20  0.911706     없을
31277     20  0.911706    인간의
31323     20  0.911706  탑골공원의
31338     20  0.911706    할배를
31339     20  0.911706     해도

[755 rows x 3 columns], R=30, lambda_step=0.01, plot_opts={'xlab': 'PC1', 'ylab': 'PC2'}, topic_order=[1, 15, 20, 5, 6, 3, 10, 12, 7, 13, 11, 19, 2, 14, 4, 18, 9, 17, 8, 16])

In [29]:
lda_vectors = pd.DataFrame(lda_output_nonstop)
lda_vectors.columns = ['Topic '+str(i) for i in range(lda_vectors.shape[1])]
lda_vectors.index = ['Document '+str(i) for i in range(lda_vectors.shape[0])]
lda_vectors.head()

Topic 0   Topic 1   Topic 2   Topic 3   Topic 4   Topic 5  \
Document 0  0.089548  0.757923  0.087145  0.003846  0.003846  0.003846   
Document 1  0.002381  0.002381  0.002381  0.002381  0.002381  0.002381   
Document 2  0.003571  0.003571  0.003571  0.003571  0.003571  0.003571   
Document 3  0.003333  0.070847  0.003333  0.003333  0.003333  0.003333   
Document 4  0.004167  0.004167  0.004167  0.004167  0.004167  0.004167   

             Topic 6   Topic 7   Topic 8   Topic 9  Topic 10  Topic 11  \
Document 0  0.003846  0.003846  0.003846  0.003846  0.003846  0.003846   
Document 1  0.002381  0.002381  0.002381  0.002381  0.002381  0.002381   
Document 2  0.003571  0.003571  0.003571  0.003571  0.003571  0.003571   
Document 3  0.003333  0.003333  0.003333  0.003333  0.003333  0.003333   
Document 4  0.004167  0.004167  0.004167  0.004167  0.004167  0.004167   

            Topic 12  Topic 13  Topic 14  Topic 15  Topic 16  Topic 17  \
Document 0  0.003846  0.003846  0.003846  0.003846  0.003846  0.003846   
Document 1  0.002381  0.002381  0.002381  0.002381  0.002381  0.002381   
Document 2  0.003571  0.003571  0.146429  0.003571  0.003571  0.789286   
Document 3  0.003333  0.003333  0.869153  0.003333  0.003333  0.003333   
Document 4  0.091250  0.640330  0.004167  0.004167  0.004167  0.004167   

            Topic 18  Topic 19  
Document 0  0.003846  0.003846  
Document 1  0.145238  0.811905  
Document 2  0.003571  0.003571  
Document 3  0.003333  0.003333  
Document 4  0.004167  0.197586

In [30]:
# Function from https://towardsdatascience.com/topic-modeling-quora-questions-with-lda-nmf-aff8dce5e1dd
import numpy as np
def show_topics(vectorizer=vectorizer, lda_model=lda_model, n_words=20):
    keywords = np.array(vectorizer.get_feature_names())
    topic_keywords = []
    for topic_weights in lda_model.components_:
        top_keyword_locs = (-topic_weights).argsort()[:n_words]
        topic_keywords.append(keywords.take(top_keyword_locs))
    return topic_keywords

topic_keywords = show_topics(vectorizer=tweets_vectorizer, lda_model=lda_model, n_words=20)

df_topic_keywords = pd.DataFrame(topic_keywords)
df_topic_keywords.columns = ['Word '+str(i) for i in range(df_topic_keywords.shape[1])]
df_topic_keywords.index = ['Topic '+str(i) for i in range(df_topic_keywords.shape[0])]
df_topic_keywords.T

Topic 0       Topic 1    Topic 2   Topic 3    Topic 4  \
Word 0     youtube         https        was     april       then   
Word 1         any            co  australia     fools       very   
Word 2       video            rt         at   friends        htt   
Word 3        long           the        off       may       guys   
Word 4       liked            to        got        el      which   
Word 5        from            in       week  thinking        isn   
Word 6        baby           for      night      rest    michael   
Word 7         ago            of       last  facebook       hair   
Word 8    watching           and         15      kind      under   
Word 9          13            on     threat      sale       nice   
Word 10     myself           amp        via       cup        his   
Word 11   adelaide          with       goes   calling   snapchat   
Word 12  president            at      years      food      round   
Word 13      learn          this         on       más       when   
Word 14    protest            is      house     worst  extremist   
Word 15         25  iheartawards       were   central      using   
Word 16    episode   bestfanarmy      after   station        one   
Word 17         wa           new         of      west       side   
Word 18      stuff           day      until      ipad       lmao   
Word 19        red          time         12      hill        buy   

                 Topic 5     Topic 6    Topic 7          Topic 8  \
Word 0              city         out         10         business   
Word 1             fight          as   predicts           voting   
Word 2         continues          of       some              own   
Word 3                من        back        fun         congrats   
Word 4           running        riot         11             data   
Word 5               por         the    fucking            party   
Word 6                في         lol      since          tornado   
Word 7                14       check    between               al   
Word 8              blue          by         km         listings   
Word 9           shooter          is       wind            guess   
Word 10       suspicious      really  following              son   
Word 11            chris         yes      doozy              ppl   
Word 12      shutdownchi        made       temp              usa   
Word 13  fightforfunding      police    falling           former   
Word 14    investigating     tonight      takes           assets   
Word 15       gostkowski        well         31             poor   
Word 16        recovered  convention         12  georgianasophia   
Word 17           nearby        didn       pips      jpdice_fox6   
Word 18         dolphins       union         mm       decreasing   
Word 19           nights          oh   comments       intangible   

                Topic 9       Topic 10    Topic 11 Topic 12 Topic 13  \
Word 0               rt             rt       https       rt      say   
Word 1               de         always          co    daddy   middle   
Word 2   constitutional            que          rt  fashion  looking   
Word 3        important            set         the    youth   sydney   
Word 4             link             eu          of  exposed   friday   
Word 5             cast             na          by       없을   around   
Word 6               si           para    activist     뒤엎어서     play   
Word 7            click          three         who      것이다     join   
Word 8           auspol  demonstration     clinton    탑골공원의      hot   
Word 9            thecw         the100          in      할배를       50   
Word 10            bill            god          at     알파고가  college   
Word 11              pm          bigot         via  abmanse   attack   
Word 12         private           soon         her    당해낼수는       40   
Word 13         funding          words     hillary      아무리  perfect   
Word 14       shaunking          india          on      승부를     film   
W